### PR TITLE
Fix #25 by adding `.get`.

### LINKED ISSUE #25: error
PS C:\Users\usuario\Downloads\BingGPT-Discord-Bot> python src/bot.py
Traceback (most recent call last):
  File "C:\Users\usuario\Downloads\BingGPT-Discord-Bot\src\bot.py", line 44, in <module>
    gptbot = Chatbot(cookie_path='cookies.json')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usuario\Downloads\BingGPT-Discord-Bot\src\EdgeGPT.py", line 603, in __init__
    self.chat_hub: _ChatHub = _ChatHub(
                              ^^^^^^^^^
  File "C:\Users\usuario\Downloads\BingGPT-Discord-Bot\src\EdgeGPT.py", line 415, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'conversationSignature'

### PR DESCRIPTION
**Pull request by Fairuz-Afdhal**

### CODE REVIEW

**Comment by ediziks** [comment]
Thanks for raising a PR. Did you have a chance to test the bot after the changes?

**Comment by Fairuz-Afdhal** [comment]
> Thanks for raising a PR. Did you have a chance to test the bot after the changes?

Yes I did, currently running it now on my VPS.

**Comment by ediziks** [comment]
Do you mean you're able to run /imagine command only, or together with /ask as well?

**Comment by Fairuz-Afdhal** [comment]
> Do you mean you're able to run /imagine command only, or together with /ask as well?

It doesn't seem to fix /ask, sorry. Please take a look at my other PR.

**Comment by ediziks** [comment]
still seems like an update on /imagine so merging. thanks for suggesting

**Review by ediziks — APPROVED** [review]

**Pull request merged**
